// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--dev
// source: proto/manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 通用响应头结构
type ReplyHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyHeader) Reset() {
	*x = ReplyHeader{}
	mi := &file_proto_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyHeader) ProtoMessage() {}

func (x *ReplyHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyHeader.ProtoReflect.Descriptor instead.
func (*ReplyHeader) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ReplyHeader) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReplyHeader) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *StatusData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_proto_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{1}
}

func (x *StatusReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *StatusReply) GetData() *StatusData {
	if x != nil {
		return x.Data
	}
	return nil
}

type StatusData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Regions       []string               `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
	ClientCount   int32                  `protobuf:"varint,3,opt,name=client_count,json=clientCount,proto3" json:"client_count,omitempty"`
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusData) Reset() {
	*x = StatusData{}
	mi := &file_proto_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusData) ProtoMessage() {}

func (x *StatusData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusData.ProtoReflect.Descriptor instead.
func (*StatusData) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{2}
}

func (x *StatusData) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *StatusData) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *StatusData) GetClientCount() int32 {
	if x != nil {
		return x.ClientCount
	}
	return 0
}

func (x *StatusData) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LoginData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	TwoStepCode   string                 `protobuf:"bytes,3,opt,name=two_step_code,json=twoStepCode,proto3" json:"two_step_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_proto_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{4}
}

func (x *LoginData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginData) GetTwoStepCode() string {
	if x != nil {
		return x.TwoStepCode
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *LoginData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	mi := &file_proto_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{5}
}

func (x *LoginReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LoginReply) GetData() *LoginData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LogoutData            `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{6}
}

func (x *LogoutRequest) GetData() *LogoutData {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogoutData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutData) Reset() {
	*x = LogoutData{}
	mi := &file_proto_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutData) ProtoMessage() {}

func (x *LogoutData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutData.ProtoReflect.Descriptor instead.
func (*LogoutData) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{7}
}

func (x *LogoutData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *LogoutData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_proto_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{8}
}

func (x *LogoutReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LogoutReply) GetData() *LogoutData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DecryptData           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_proto_manager_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{9}
}

func (x *DecryptRequest) GetData() *DecryptData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DecryptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *DecryptData           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptReply) Reset() {
	*x = DecryptReply{}
	mi := &file_proto_manager_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptReply) ProtoMessage() {}

func (x *DecryptReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptReply.ProtoReflect.Descriptor instead.
func (*DecryptReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{10}
}

func (x *DecryptReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DecryptReply) GetData() *DecryptData {
	if x != nil {
		return x.Data
	}
	return nil
}

type DecryptData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	SampleIndex   int32                  `protobuf:"varint,3,opt,name=sample_index,json=sampleIndex,proto3" json:"sample_index,omitempty"`
	Sample        []byte                 `protobuf:"bytes,4,opt,name=sample,proto3" json:"sample,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptData) Reset() {
	*x = DecryptData{}
	mi := &file_proto_manager_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptData) ProtoMessage() {}

func (x *DecryptData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptData.ProtoReflect.Descriptor instead.
func (*DecryptData) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{11}
}

func (x *DecryptData) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *DecryptData) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DecryptData) GetSampleIndex() int32 {
	if x != nil {
		return x.SampleIndex
	}
	return 0
}

func (x *DecryptData) GetSample() []byte {
	if x != nil {
		return x.Sample
	}
	return nil
}

type M3U8Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *M3U8DataRequest       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M3U8Request) Reset() {
	*x = M3U8Request{}
	mi := &file_proto_manager_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M3U8Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M3U8Request) ProtoMessage() {}

func (x *M3U8Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M3U8Request.ProtoReflect.Descriptor instead.
func (*M3U8Request) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{12}
}

func (x *M3U8Request) GetData() *M3U8DataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type M3U8DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M3U8DataRequest) Reset() {
	*x = M3U8DataRequest{}
	mi := &file_proto_manager_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M3U8DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M3U8DataRequest) ProtoMessage() {}

func (x *M3U8DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M3U8DataRequest.ProtoReflect.Descriptor instead.
func (*M3U8DataRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{13}
}

func (x *M3U8DataRequest) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

type M3U8Reply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *M3U8DataResponse      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M3U8Reply) Reset() {
	*x = M3U8Reply{}
	mi := &file_proto_manager_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M3U8Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M3U8Reply) ProtoMessage() {}

func (x *M3U8Reply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M3U8Reply.ProtoReflect.Descriptor instead.
func (*M3U8Reply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{14}
}

func (x *M3U8Reply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *M3U8Reply) GetData() *M3U8DataResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type M3U8DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	M3U8          string                 `protobuf:"bytes,2,opt,name=m3u8,proto3" json:"m3u8,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *M3U8DataResponse) Reset() {
	*x = M3U8DataResponse{}
	mi := &file_proto_manager_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *M3U8DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*M3U8DataResponse) ProtoMessage() {}

func (x *M3U8DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use M3U8DataResponse.ProtoReflect.Descriptor instead.
func (*M3U8DataResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{15}
}

func (x *M3U8DataResponse) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *M3U8DataResponse) GetM3U8() string {
	if x != nil {
		return x.M3U8
	}
	return ""
}

type LyricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LyricsDataRequest     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LyricsRequest) Reset() {
	*x = LyricsRequest{}
	mi := &file_proto_manager_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LyricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LyricsRequest) ProtoMessage() {}

func (x *LyricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LyricsRequest.ProtoReflect.Descriptor instead.
func (*LyricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{16}
}

func (x *LyricsRequest) GetData() *LyricsDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type LyricsDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LyricsDataRequest) Reset() {
	*x = LyricsDataRequest{}
	mi := &file_proto_manager_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LyricsDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LyricsDataRequest) ProtoMessage() {}

func (x *LyricsDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LyricsDataRequest.ProtoReflect.Descriptor instead.
func (*LyricsDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{17}
}

func (x *LyricsDataRequest) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *LyricsDataRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LyricsDataRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type LyricsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *LyricsDataResponse    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LyricsReply) Reset() {
	*x = LyricsReply{}
	mi := &file_proto_manager_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LyricsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LyricsReply) ProtoMessage() {}

func (x *LyricsReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LyricsReply.ProtoReflect.Descriptor instead.
func (*LyricsReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{18}
}

func (x *LyricsReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LyricsReply) GetData() *LyricsDataResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type LyricsDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	Lyrics        string                 `protobuf:"bytes,2,opt,name=lyrics,proto3" json:"lyrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LyricsDataResponse) Reset() {
	*x = LyricsDataResponse{}
	mi := &file_proto_manager_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LyricsDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LyricsDataResponse) ProtoMessage() {}

func (x *LyricsDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LyricsDataResponse.ProtoReflect.Descriptor instead.
func (*LyricsDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{19}
}

func (x *LyricsDataResponse) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *LyricsDataResponse) GetLyrics() string {
	if x != nil {
		return x.Lyrics
	}
	return ""
}

type LicenseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *LicenseDataRequest    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseRequest) Reset() {
	*x = LicenseRequest{}
	mi := &file_proto_manager_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseRequest) ProtoMessage() {}

func (x *LicenseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseRequest.ProtoReflect.Descriptor instead.
func (*LicenseRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{20}
}

func (x *LicenseRequest) GetData() *LicenseDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type LicenseDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	Challenge     string                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Uri           string                 `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseDataRequest) Reset() {
	*x = LicenseDataRequest{}
	mi := &file_proto_manager_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseDataRequest) ProtoMessage() {}

func (x *LicenseDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseDataRequest.ProtoReflect.Descriptor instead.
func (*LicenseDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{21}
}

func (x *LicenseDataRequest) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *LicenseDataRequest) GetChallenge() string {
	if x != nil {
		return x.Challenge
	}
	return ""
}

func (x *LicenseDataRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type LicenseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *LicenseDataResponse   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseReply) Reset() {
	*x = LicenseReply{}
	mi := &file_proto_manager_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseReply) ProtoMessage() {}

func (x *LicenseReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseReply.ProtoReflect.Descriptor instead.
func (*LicenseReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{22}
}

func (x *LicenseReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LicenseReply) GetData() *LicenseDataResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type LicenseDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	License       string                 `protobuf:"bytes,2,opt,name=license,proto3" json:"license,omitempty"`
	Renew         int64                  `protobuf:"varint,3,opt,name=renew,proto3" json:"renew,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseDataResponse) Reset() {
	*x = LicenseDataResponse{}
	mi := &file_proto_manager_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseDataResponse) ProtoMessage() {}

func (x *LicenseDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseDataResponse.ProtoReflect.Descriptor instead.
func (*LicenseDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{23}
}

func (x *LicenseDataResponse) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *LicenseDataResponse) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *LicenseDataResponse) GetRenew() int64 {
	if x != nil {
		return x.Renew
	}
	return 0
}

type WebPlaybackRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Data          *WebPlaybackDataRequest `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPlaybackRequest) Reset() {
	*x = WebPlaybackRequest{}
	mi := &file_proto_manager_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPlaybackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPlaybackRequest) ProtoMessage() {}

func (x *WebPlaybackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPlaybackRequest.ProtoReflect.Descriptor instead.
func (*WebPlaybackRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{24}
}

func (x *WebPlaybackRequest) GetData() *WebPlaybackDataRequest {
	if x != nil {
		return x.Data
	}
	return nil
}

type WebPlaybackDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPlaybackDataRequest) Reset() {
	*x = WebPlaybackDataRequest{}
	mi := &file_proto_manager_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPlaybackDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPlaybackDataRequest) ProtoMessage() {}

func (x *WebPlaybackDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPlaybackDataRequest.ProtoReflect.Descriptor instead.
func (*WebPlaybackDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{25}
}

func (x *WebPlaybackDataRequest) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

type WebPlaybackReply struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Header        *ReplyHeader             `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Data          *WebPlaybackDataResponse `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPlaybackReply) Reset() {
	*x = WebPlaybackReply{}
	mi := &file_proto_manager_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPlaybackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPlaybackReply) ProtoMessage() {}

func (x *WebPlaybackReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPlaybackReply.ProtoReflect.Descriptor instead.
func (*WebPlaybackReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{26}
}

func (x *WebPlaybackReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *WebPlaybackReply) GetData() *WebPlaybackDataResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type WebPlaybackDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdamId        string                 `protobuf:"bytes,1,opt,name=adam_id,json=adamId,proto3" json:"adam_id,omitempty"`
	M3U8          string                 `protobuf:"bytes,2,opt,name=m3u8,proto3" json:"m3u8,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebPlaybackDataResponse) Reset() {
	*x = WebPlaybackDataResponse{}
	mi := &file_proto_manager_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPlaybackDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPlaybackDataResponse) ProtoMessage() {}

func (x *WebPlaybackDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPlaybackDataResponse.ProtoReflect.Descriptor instead.
func (*WebPlaybackDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{27}
}

func (x *WebPlaybackDataResponse) GetAdamId() string {
	if x != nil {
		return x.AdamId
	}
	return ""
}

func (x *WebPlaybackDataResponse) GetM3U8() string {
	if x != nil {
		return x.M3U8
	}
	return ""
}

type ErrorReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ReplyHeader           `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorReply) Reset() {
	*x = ErrorReply{}
	mi := &file_proto_manager_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorReply) ProtoMessage() {}

func (x *ErrorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manager_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorReply.ProtoReflect.Descriptor instead.
func (*ErrorReply) Descriptor() ([]byte, []int) {
	return file_proto_manager_proto_rawDescGZIP(), []int{28}
}

func (x *ErrorReply) GetHeader() *ReplyHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_proto_manager_proto protoreflect.FileDescriptor

const file_proto_manager_proto_rawDesc = "" +
	"\n" +
	"\x13proto/manager.proto\x12\n" +
	"manager.v1\x1a\x1bgoogle/protobuf/empty.proto\"3\n" +
	"\vReplyHeader\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"j\n" +
	"\vStatusReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.manager.v1.StatusDataR\x04data\"w\n" +
	"\n" +
	"StatusData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\aregions\x18\x02 \x03(\tR\aregions\x12!\n" +
	"\fclient_count\x18\x03 \x01(\x05R\vclientCount\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\"9\n" +
	"\fLoginRequest\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.manager.v1.LoginDataR\x04data\"g\n" +
	"\tLoginData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\"\n" +
	"\rtwo_step_code\x18\x03 \x01(\tR\vtwoStepCode\"h\n" +
	"\n" +
	"LoginReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.manager.v1.LoginDataR\x04data\";\n" +
	"\rLogoutRequest\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.manager.v1.LogoutDataR\x04data\"(\n" +
	"\n" +
	"LogoutData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"j\n" +
	"\vLogoutReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x12*\n" +
	"\x04data\x18\x02 \x01(\v2\x16.manager.v1.LogoutDataR\x04data\"=\n" +
	"\x0eDecryptRequest\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.manager.v1.DecryptDataR\x04data\"l\n" +
	"\fDecryptReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.manager.v1.DecryptDataR\x04data\"s\n" +
	"\vDecryptData\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12!\n" +
	"\fsample_index\x18\x03 \x01(\x05R\vsampleIndex\x12\x16\n" +
	"\x06sample\x18\x04 \x01(\fR\x06sample\">\n" +
	"\vM3U8Request\x12/\n" +
	"\x04data\x18\x01 \x01(\v2\x1b.manager.v1.M3U8DataRequestR\x04data\"*\n" +
	"\x0fM3U8DataRequest\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\"n\n" +
	"\tM3U8Reply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1c.manager.v1.M3U8DataResponseR\x04data\"?\n" +
	"\x10M3U8DataResponse\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x12\n" +
	"\x04m3u8\x18\x02 \x01(\tR\x04m3u8\"B\n" +
	"\rLyricsRequest\x121\n" +
	"\x04data\x18\x01 \x01(\v2\x1d.manager.v1.LyricsDataRequestR\x04data\"`\n" +
	"\x11LyricsDataRequest\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"r\n" +
	"\vLyricsReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.manager.v1.LyricsDataResponseR\x04data\"E\n" +
	"\x12LyricsDataResponse\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x16\n" +
	"\x06lyrics\x18\x02 \x01(\tR\x06lyrics\"D\n" +
	"\x0eLicenseRequest\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x1e.manager.v1.LicenseDataRequestR\x04data\"]\n" +
	"\x12LicenseDataRequest\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\tR\tchallenge\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\"t\n" +
	"\fLicenseReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x123\n" +
	"\x04data\x18\x02 \x01(\v2\x1f.manager.v1.LicenseDataResponseR\x04data\"^\n" +
	"\x13LicenseDataResponse\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x18\n" +
	"\alicense\x18\x02 \x01(\tR\alicense\x12\x14\n" +
	"\x05renew\x18\x03 \x01(\x03R\x05renew\"L\n" +
	"\x12WebPlaybackRequest\x126\n" +
	"\x04data\x18\x01 \x01(\v2\".manager.v1.WebPlaybackDataRequestR\x04data\"1\n" +
	"\x16WebPlaybackDataRequest\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\"|\n" +
	"\x10WebPlaybackReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.manager.v1.WebPlaybackDataResponseR\x04data\"F\n" +
	"\x17WebPlaybackDataResponse\x12\x17\n" +
	"\aadam_id\x18\x01 \x01(\tR\x06adamId\x12\x12\n" +
	"\x04m3u8\x18\x02 \x01(\tR\x04m3u8\"=\n" +
	"\n" +
	"ErrorReply\x12/\n" +
	"\x06header\x18\x01 \x01(\v2\x17.manager.v1.ReplyHeaderR\x06header2\x98\x04\n" +
	"\x15WrapperManagerService\x129\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x17.manager.v1.StatusReply\x12=\n" +
	"\x05Login\x12\x18.manager.v1.LoginRequest\x1a\x16.manager.v1.LoginReply(\x010\x01\x12<\n" +
	"\x06Logout\x12\x19.manager.v1.LogoutRequest\x1a\x17.manager.v1.LogoutReply\x12C\n" +
	"\aDecrypt\x12\x1a.manager.v1.DecryptRequest\x1a\x18.manager.v1.DecryptReply(\x010\x01\x126\n" +
	"\x04M3U8\x12\x17.manager.v1.M3U8Request\x1a\x15.manager.v1.M3U8Reply\x12<\n" +
	"\x06Lyrics\x12\x19.manager.v1.LyricsRequest\x1a\x17.manager.v1.LyricsReply\x12?\n" +
	"\aLicense\x12\x1a.manager.v1.LicenseRequest\x1a\x18.manager.v1.LicenseReply\x12K\n" +
	"\vWebPlayback\x12\x1e.manager.v1.WebPlaybackRequest\x1a\x1c.manager.v1.WebPlaybackReplyB\x1dZ\x1bwrapper-manager/proto;protob\x06proto3"

var (
	file_proto_manager_proto_rawDescOnce sync.Once
	file_proto_manager_proto_rawDescData []byte
)

func file_proto_manager_proto_rawDescGZIP() []byte {
	file_proto_manager_proto_rawDescOnce.Do(func() {
		file_proto_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)))
	})
	return file_proto_manager_proto_rawDescData
}

var file_proto_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_manager_proto_goTypes = []any{
	(*ReplyHeader)(nil),             // 0: manager.v1.ReplyHeader
	(*StatusReply)(nil),             // 1: manager.v1.StatusReply
	(*StatusData)(nil),              // 2: manager.v1.StatusData
	(*LoginRequest)(nil),            // 3: manager.v1.LoginRequest
	(*LoginData)(nil),               // 4: manager.v1.LoginData
	(*LoginReply)(nil),              // 5: manager.v1.LoginReply
	(*LogoutRequest)(nil),           // 6: manager.v1.LogoutRequest
	(*LogoutData)(nil),              // 7: manager.v1.LogoutData
	(*LogoutReply)(nil),             // 8: manager.v1.LogoutReply
	(*DecryptRequest)(nil),          // 9: manager.v1.DecryptRequest
	(*DecryptReply)(nil),            // 10: manager.v1.DecryptReply
	(*DecryptData)(nil),             // 11: manager.v1.DecryptData
	(*M3U8Request)(nil),             // 12: manager.v1.M3U8Request
	(*M3U8DataRequest)(nil),         // 13: manager.v1.M3U8DataRequest
	(*M3U8Reply)(nil),               // 14: manager.v1.M3U8Reply
	(*M3U8DataResponse)(nil),        // 15: manager.v1.M3U8DataResponse
	(*LyricsRequest)(nil),           // 16: manager.v1.LyricsRequest
	(*LyricsDataRequest)(nil),       // 17: manager.v1.LyricsDataRequest
	(*LyricsReply)(nil),             // 18: manager.v1.LyricsReply
	(*LyricsDataResponse)(nil),      // 19: manager.v1.LyricsDataResponse
	(*LicenseRequest)(nil),          // 20: manager.v1.LicenseRequest
	(*LicenseDataRequest)(nil),      // 21: manager.v1.LicenseDataRequest
	(*LicenseReply)(nil),            // 22: manager.v1.LicenseReply
	(*LicenseDataResponse)(nil),     // 23: manager.v1.LicenseDataResponse
	(*WebPlaybackRequest)(nil),      // 24: manager.v1.WebPlaybackRequest
	(*WebPlaybackDataRequest)(nil),  // 25: manager.v1.WebPlaybackDataRequest
	(*WebPlaybackReply)(nil),        // 26: manager.v1.WebPlaybackReply
	(*WebPlaybackDataResponse)(nil), // 27: manager.v1.WebPlaybackDataResponse
	(*ErrorReply)(nil),              // 28: manager.v1.ErrorReply
	(*emptypb.Empty)(nil),           // 29: google.protobuf.Empty
}
var file_proto_manager_proto_depIdxs = []int32{
	0,  // 0: manager.v1.StatusReply.header:type_name -> manager.v1.ReplyHeader
	2,  // 1: manager.v1.StatusReply.data:type_name -> manager.v1.StatusData
	4,  // 2: manager.v1.LoginRequest.data:type_name -> manager.v1.LoginData
	0,  // 3: manager.v1.LoginReply.header:type_name -> manager.v1.ReplyHeader
	4,  // 4: manager.v1.LoginReply.data:type_name -> manager.v1.LoginData
	7,  // 5: manager.v1.LogoutRequest.data:type_name -> manager.v1.LogoutData
	0,  // 6: manager.v1.LogoutReply.header:type_name -> manager.v1.ReplyHeader
	7,  // 7: manager.v1.LogoutReply.data:type_name -> manager.v1.LogoutData
	11, // 8: manager.v1.DecryptRequest.data:type_name -> manager.v1.DecryptData
	0,  // 9: manager.v1.DecryptReply.header:type_name -> manager.v1.ReplyHeader
	11, // 10: manager.v1.DecryptReply.data:type_name -> manager.v1.DecryptData
	13, // 11: manager.v1.M3U8Request.data:type_name -> manager.v1.M3U8DataRequest
	0,  // 12: manager.v1.M3U8Reply.header:type_name -> manager.v1.ReplyHeader
	15, // 13: manager.v1.M3U8Reply.data:type_name -> manager.v1.M3U8DataResponse
	17, // 14: manager.v1.LyricsRequest.data:type_name -> manager.v1.LyricsDataRequest
	0,  // 15: manager.v1.LyricsReply.header:type_name -> manager.v1.ReplyHeader
	19, // 16: manager.v1.LyricsReply.data:type_name -> manager.v1.LyricsDataResponse
	21, // 17: manager.v1.LicenseRequest.data:type_name -> manager.v1.LicenseDataRequest
	0,  // 18: manager.v1.LicenseReply.header:type_name -> manager.v1.ReplyHeader
	23, // 19: manager.v1.LicenseReply.data:type_name -> manager.v1.LicenseDataResponse
	25, // 20: manager.v1.WebPlaybackRequest.data:type_name -> manager.v1.WebPlaybackDataRequest
	0,  // 21: manager.v1.WebPlaybackReply.header:type_name -> manager.v1.ReplyHeader
	27, // 22: manager.v1.WebPlaybackReply.data:type_name -> manager.v1.WebPlaybackDataResponse
	0,  // 23: manager.v1.ErrorReply.header:type_name -> manager.v1.ReplyHeader
	29, // 24: manager.v1.WrapperManagerService.Status:input_type -> google.protobuf.Empty
	3,  // 25: manager.v1.WrapperManagerService.Login:input_type -> manager.v1.LoginRequest
	6,  // 26: manager.v1.WrapperManagerService.Logout:input_type -> manager.v1.LogoutRequest
	9,  // 27: manager.v1.WrapperManagerService.Decrypt:input_type -> manager.v1.DecryptRequest
	12, // 28: manager.v1.WrapperManagerService.M3U8:input_type -> manager.v1.M3U8Request
	16, // 29: manager.v1.WrapperManagerService.Lyrics:input_type -> manager.v1.LyricsRequest
	20, // 30: manager.v1.WrapperManagerService.License:input_type -> manager.v1.LicenseRequest
	24, // 31: manager.v1.WrapperManagerService.WebPlayback:input_type -> manager.v1.WebPlaybackRequest
	1,  // 32: manager.v1.WrapperManagerService.Status:output_type -> manager.v1.StatusReply
	5,  // 33: manager.v1.WrapperManagerService.Login:output_type -> manager.v1.LoginReply
	8,  // 34: manager.v1.WrapperManagerService.Logout:output_type -> manager.v1.LogoutReply
	10, // 35: manager.v1.WrapperManagerService.Decrypt:output_type -> manager.v1.DecryptReply
	14, // 36: manager.v1.WrapperManagerService.M3U8:output_type -> manager.v1.M3U8Reply
	18, // 37: manager.v1.WrapperManagerService.Lyrics:output_type -> manager.v1.LyricsReply
	22, // 38: manager.v1.WrapperManagerService.License:output_type -> manager.v1.LicenseReply
	26, // 39: manager.v1.WrapperManagerService.WebPlayback:output_type -> manager.v1.WebPlaybackReply
	32, // [32:40] is the sub-list for method output_type
	24, // [24:32] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_proto_manager_proto_init() }
func file_proto_manager_proto_init() {
	if File_proto_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manager_proto_rawDesc), len(file_proto_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manager_proto_goTypes,
		DependencyIndexes: file_proto_manager_proto_depIdxs,
		MessageInfos:      file_proto_manager_proto_msgTypes,
	}.Build()
	File_proto_manager_proto = out.File
	file_proto_manager_proto_goTypes = nil
	file_proto_manager_proto_depIdxs = nil
}
